# -*- coding: utf-8 -*-
"""sisop neww.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I6_KnVgxuvu_FOgWwVtFLpskvE-olGxs
"""

import random

#untuk tampilan awalan
print('''
                    +---------------------------------------+
                    | Welcome to games tebak kata buah🍎!! |
                    +---------------------------------------+                  
                    ''')

pemain = input("What is your nickname?")
print(f"Good luck and enjoyy the games {pemain}❤️")
print()

def choose():
  print('-' *50)
  print('Ready to start game tebak kata buah?')
  print('a. Yes, want to play')
  print('b. No, choose another game')

def buah():
  namebuah = ['mangga',
            'delima',
            'semangka',
            'jeruk',
            'pisang',
            'nanas', 
            'anggur',
            'apel',
            'pir',
            'alpukat',
            'kelapa',
            'jambu']
  pilihanbuah = random.choice(namebuah)
  return pilihanbuah

def cektebakan(parsekata,huruftebakan=None): # cek apakah huruf ada dikata
    if huruftebakan in parsekata:
        return True
    else:
        return False
    
def hitunginput(huruftebakan): # menghitung jumlah input tebakan
    count = 0
    for i in huruftebakan:
        count += 1
    return count

def progresskata(parsekata,progress,huruftebakan=None): # fungsi tebak per 1 kata
    if progress == None: # jika game baru di mulai progress masih *semua
        progress = []
        for i in parsekata:
            progress.append('_')
    for i in (i for i,x in enumerate(parsekata) if x == huruftebakan):
        progress[i] = str(huruftebakan) # ubah _ jd huruf
    return progress

def tebaklangsung(parsekata,huruftebakan): # fungsi tebakan langsung
    kata = ''.join(parsekata)
    tebak = ''.join(huruftebakan)
    if kata == tebak:
        return True
    else:
        return False

def cekselesai(progress): # cek progress kata yang di tebak
    ada = -1
    for i in (i for i,x in enumerate(progress) if x == '_'):
        ada = i
    if ada != -1:
        return True
    else:
        return False

def join(kata): # menggabungkan isi list
    kata = ' '.join(kata)
    return kata

def sudahdipilih(baghuruf,pilihan): # fungsi cek huruf pernah dipilih
    ada = -1
    for i in (i for i,x in enumerate(baghuruf) if x == pilihan):
        ada = i
    if ada != -1:
        return True
    else:
        return False

choose()
choosen = input('your choice: ')

print('=='*26)
print('\n')
if choosen == "a":
  buah()

def main():
    kata = buah()
    parsekata = list(kata)
    panjangkata = len(parsekata)
    progress = None
    tertebak = False
    telahdipilih = []
    
    langkah = 0
    while not tertebak:
        print('Clue dibawah ini berisi %d huruf, ' %panjangkata, end='')
        huruftebakan = input('kuyy tebak 1 huruf: ')
        jmltebakan = hitunginput(huruftebakan)
        if jmltebakan == 1: # jika input hanya 1 huruf
            # S: cek huruf sudah pernah di pilih
            cektlhdipilih = sudahdipilih(telahdipilih,huruftebakan)
            if cektlhdipilih:
                print('Kamu sudah menebak huruf %s sebelumnya, cari huruf yg lain ya.' %huruftebakan)
                print(join(progress))
                continue # lansung langkah berikutnya
            else:
                telahdipilih.append(huruftebakan)
            # E: cek huruf sudah pernah di pilih

            # S: cek jika huruf tebakan ada dalam kata
            cek_ada = cektebakan(parsekata,huruftebakan)
            if cek_ada:
                progress = progresskata(parsekata,progress,huruftebakan)
                print(join(progress))
            else:
                print('Tidak mengandung huruf ', huruftebakan)
                print(join(progress))
            
            selesai = cekselesai(progress)
            if not selesai:
                print('''
                    +------------------------------------+
                    | GOOD JOB! tebakan kamu berhasil😆! |
                    +------------------------------------+
                    ''')
                print('kata buah ''%s'' terpecahkan dalam %d langkah nih, kerenn bgt!' %(join(parsekata),langkah))
                tertebak = True
                
        else: # jika input lebih dari 1 huruf
            if jmltebakan == 0: # tidak ada input
                print('Tidak ada input, masukkan satu huruf.')
                print(join(progress))
            else: # input lebih dari satu, tebakan langsung
                langsung = tebaklangsung(parsekata,huruftebakan)
                if langsung == True: # jika tebakan langsung benar
                    print('''
                    +--------------------------------------------+
                    | Selamat tebakan langsung anda BERHASIL !!! |
                    +--------------------------------------------+
                    ''')
                    print('kata ''%s'' tertebak dalam %d langkah.' %(join(parsekata),langkah))
                    tertebak = True
                    
                else: # tebakan langsung salah
                    print('Tebakan langsung', pemain, 'yach masih salah:(')
                    print(join(progress))
        langkah += 1
main()


