print ("------------------------------------")
print ("Tugas 1 SISOP Kelas A")
print ("------------------------------------")
print ("Nama : Aniysah Fauziyyah Alfa")
print ("NPM  : 21083010083")
print ("------------------------------------")
print ("notes: jangan lupa bahagiaa")
print ("------------------------------------")
print ("Halo dunia!")
print ("Ini adalah skrip Bash pertamaku di Linux")
